
/*
* this file defines some rather odd, and/or deprecated stuff.
* it is in the public domain. use it however you want!
*/

#pragma once

#if (defined(_WIN32) || defined(__CYGWIN__))
    #include <windows.h>
    #include <tchar.h>
    //#include <mbctype.h>
    #define filelength _filelength
    #define splitpath _splitpath
    #define makepath _makepath
    #if defined(__CYGWIN__)
        #define stricmp strcasecmp
    #else
        #define strdup _strdup
        #define mkdir _mkdir
        #define stricmp _stricmp
        #define fileno _fileno
    #endif
#endif

/*begin stuff generated by gdefs.rb ... */
#if !defined(_MAX_PATH)
    #if defined(MAX_PATH)
        #define _MAX_PATH MAX_PATH
    #else
        #define _MAX_PATH 260
        #define MAX_PATH _MAX_PATH
    #endif
#endif
#if !defined(_MAX_EXT)
    #if defined(MAX_EXT)
        #define _MAX_EXT MAX_EXT
    #else
        #define _MAX_EXT 50
        #define MAX_EXT _MAX_EXT
    #endif
#endif
#if !defined(_MAX_DRIVE)
    #if defined(MAX_DRIVE)
        #define _MAX_DRIVE MAX_DRIVE
    #else
        #define _MAX_DRIVE 5
        #define MAX_DRIVE _MAX_DRIVE
    #endif
#endif
#if !defined(_MAX_FNAME)
    #if defined(MAX_FNAME)
        #define _MAX_FNAME MAX_FNAME
    #else
        #define _MAX_FNAME 256
        #define MAX_FNAME _MAX_FNAME
    #endif
#endif
#if !defined(_MAX_DIR)
    #if defined(MAX_DIR)
        #define _MAX_DIR MAX_DIR
    #else
        #define _MAX_DIR 256
        #define MAX_DIR _MAX_DIR
    #endif
#endif
/* end stuff generated by gdefs.rb */
