#!/usr/bin/ruby -w

# most of these were grepped from either the vs runtime sources, or
# (really, really) old windows-specific runtimes. i can't guarantee
# these are correct, or won't blow up in your face. sorry
VALS = {
  "MAX_PATH"  => "260",
  "MAX_EXT"   => "50",
  "MAX_DRIVE" => "5",
  "MAX_FNAME" => "256",
  "MAX_DIR"   => "256",
}

## i think, originally, underscored names are defined first, but it's
## not exactly clear...
TEMPLATE = <<__eos__
#if !defined(%{oldname})
    #if defined(%{plainname})
        #define %{oldname} %{plainname}
    #else
        #define %{oldname} %{value}
        #define %{plainname} %{oldname}
    #endif
#endif
__eos__

## in this template, the non-underscored name is defined first
ALT_TEMPLATE = <<__eos__
#if !defined(%{plainname})
  #define %{plainname} %{value}
#endif
#if !defined(%{oldname})
  #define %{oldname} %{plainname}
#endif
__eos__



begin
  printf("/*begin stuff generated by gdefs.rb ... */\n")
  VALS.each do |n, v|
    printf(TEMPLATE, plainname: n, oldname: ("_" + n), value: v)
  end
  printf("/* end stuff generated by gdefs.rb */\n")
end
